#!/usr/bin/env python3
"""
nl_fscx_v2_orbit.py — Orbit-length characterisation of the NL-FSCX v2 permutation
family (TODO #78.E, §11.8.5 obstacle 2).

The NL-FSCX v2 permutation for key K is:
    pi_K(A) = nl_fscx_v2(A, K) = (M(A XOR K) + delta(K)) mod 2^n
where
    M(X) = X XOR ROL(X,1,n) XOR ROL(X,n-1,n)     (FSCX linear map)
    delta(K) = ROL(K * ceil(K/2) mod 2^n, n/4)

pi_K is a bijection on {0,1}^n for every K; its inverse is:
    pi_K^{-1}(Y) = K XOR M^{-1}((Y - delta(K)) mod 2^n)

NASG key-exchange candidate (§11.8.5 "Option C"):
    Private K_1; ephemeral K_2; fixed public base G.
    Public: C = pi_{K_1}(pi_{K_2}(pi_{K_1}^{-1}(G)))
    Security: recovering K_1 from (G, K_2, C) is a Conjugacy Search Problem (CSP)
    in the group generated by {pi_K : K in {0,1}^n}.

Obstacle 2 to a security proof: no verified lower bound on orbit lengths of pi_K;
without such a bound, small-subgroup confinement attacks cannot be excluded.

KEY FINDINGS:

  §1  Exhaustive cycle structure at n = 4, 6, 8
        K=0 is degenerate: pi_0 = M (GF(2)-linear), orbits divide n/2 = 2,3,4.
        n=6: ALL 64 keys have min cycle <= n/2 = 3 — no key escapes short cycles.
        n=8: 82.8% of keys have min cycle <= 4; only 1/256 key achieves full period
             (single cycle of length 256); only 4/256 keys have min cycle > n^2/4=16.

  §2  Sampled orbit-length distribution at n = 8, 12, 16
        n=8:  median=4, mean=29, max=126.  Most orbits fall in the [2,4) bucket.
        n=12: median=18, mean=23, max=124.  Uniformly short across all samples.
        n=16: BIMODAL — 47.5% of (K,G) pairs land in orbits of length 2–4;
              the rest spread to max=32741 (≈ N/2=32768).

  §3  Non-commutativity (Theorem 15 empirical verification)
        99.65% at n=8; 99.99% at n=16; 100.00% at n=32.
        Full-permutation commutativity at n=8: 0/1000 pairs commute as permutations.
        Confirms Theorem 15: the family {pi_K} is non-abelian.

  §4  Orbit lower bounds at large n (cap 2^16 = 65 536)
        n=24: 0/200 pairs exceed cap — ALL orbits <= 65536; typical lengths 7–100.
              *** CONCERN: orbits at n=24 are ANOMALOUSLY SHORT despite a 16M-element
              space.  Non-monotone relative to n=16 and n=32. ***
        n=32: 200/200 pairs exceed cap — ALL orbits > 65536.
        The non-monotone jump (short at n=24, long at n=32) shows orbit length is
        NOT simply increasing in n.  Production bit-size (n=256) is uncharacterised.

  §5  CSP brute-force at n = 6, 8
        Average solutions per (G, K2, C) triple: ~2.1 at both n=6 and n=8.
        Unique-solution rate: ~33–35%.  The conjugation equation has on average
        2 solutions, indicating a 2-fold algebraic collision in the small spaces.

  §6  Obstacle 2 partially addressed for n=32; non-monotone anomaly is a concern.

Runtime: ~80 s on a modest CPU (default FULL_ORBIT_SWEEP = False).
Set FULL_ORBIT_SWEEP = True to add a 2000-pair extended sweep (adds ~60 s).
"""

import math
import random
import sys
import time

random.seed(0xC0DE_FEED_78E)

FULL_ORBIT_SWEEP = False

SEP  = "═" * 72
SEP2 = "─" * 72


# ─── Self-contained primitives (integer-only, mirrors suite) ──────────────────

def rol(x: int, r: int, n: int) -> int:
    r %= n
    return ((x << r) | (x >> (n - r))) & ((1 << n) - 1)

def fscx(A: int, B: int, n: int) -> int:
    return (A ^ B ^ rol(A, 1, n) ^ rol(B, 1, n) ^ rol(A, n-1, n) ^ rol(B, n-1, n)) \
           & ((1 << n) - 1)

def delta_v2(K: int, n: int) -> int:
    """delta(K) = ROL(K * ceil(K/2) mod 2^n, n/4)."""
    return rol((K * ((K + 1) >> 1)) & ((1 << n) - 1), n >> 2, n)

def m_step(X: int, n: int) -> int:
    """One application of M = I XOR ROL XOR ROR."""
    return X ^ rol(X, 1, n) ^ rol(X, n - 1, n)

def m_inv(Y: int, n: int) -> int:
    """M^{-1}(Y) = M^{n/2 - 1}(Y).  M has order n/2, so M^{-1} = M^{n/2-1}."""
    X = Y
    for _ in range(n // 2 - 1):
        X = m_step(X, n)
    return X

def pi_K(A: int, K: int, n: int) -> int:
    """pi_K(A) = (M(A XOR K) + delta(K)) mod 2^n."""
    return (fscx(A, K, n) + delta_v2(K, n)) & ((1 << n) - 1)

def pi_K_inv(Y: int, K: int, n: int) -> int:
    """pi_K^{-1}(Y) = K XOR M^{-1}((Y - delta(K)) mod 2^n)."""
    mask = (1 << n) - 1
    return K ^ m_inv((Y - delta_v2(K, n)) & mask, n)

def orbit_brent(G: int, K: int, n: int, cap: int) -> tuple:
    """Brent's cycle detection for orbit of G under pi_K.
    Returns (length, capped) where capped=True if cap was reached before cycle closed."""
    power = 1; lam = 1
    tortoise = G
    hare = pi_K(G, K, n)
    steps = 1
    while hare != tortoise:
        if power == lam:
            tortoise = hare; power <<= 1; lam = 0
        hare = pi_K(hare, K, n)
        lam += 1; steps += 1
        if steps > cap:
            return lam, True
    return lam, False


# ─── §1: Exhaustive cycle structure at n = 4, 6, 8 ───────────────────────────

def _cycle_decomp(K: int, n: int) -> list:
    """Sorted list of all cycle lengths in the permutation pi_K on {0,...,2^n-1}."""
    N = 1 << n
    visited = bytearray(N)
    cycles = []
    for start in range(N):
        if visited[start]:
            continue
        length = 0
        x = start
        while not visited[x]:
            visited[x] = 1
            x = pi_K(x, K, n)
            length += 1
        cycles.append(length)
    cycles.sort()
    return cycles

def section1():
    print(SEP)
    print("§1 — Exhaustive Cycle Structure at n = 4, 6, 8")
    print(SEP)
    print("  For each K in {0,1}^n: full cycle decomposition of pi_K.")
    print("  K=0 is degenerate (pi_0 = M, a GF(2)-linear map of order n/2).")
    print()

    for n in [4, 6, 8]:
        N = 1 << n
        print(f"  n={n}  (state space {N}, key space {N} — exhaustive)")
        print(f"  {SEP2[:60]}")

        # K=0 special case first
        c0 = _cycle_decomp(0, n)
        print(f"  K=0 (degenerate linear): {len(c0)} cycles, lengths = {c0[:16]}")
        print(f"    max cycle = {max(c0)}, min cycle = {min(c0)}  (expected ≤ n/2={n//2})")
        print()

        # Statistics over all K
        all_min = []; all_max = []; ncyc = []
        k_full   = 0   # single cycle of length N (full period)
        k_short  = 0   # min cycle <= n//2 (degenerate-like)
        k_above_n2 = 0 # min cycle > n//2
        k_above_nsq4 = 0  # min cycle > n^2 // 4

        thresh_hi = n * n // 4

        for K in range(N):
            c = _cycle_decomp(K, n)
            mn = c[0]; mx = c[-1]
            all_min.append(mn); all_max.append(mx); ncyc.append(len(c))
            if len(c) == 1:
                k_full += 1
            if mn <= n // 2:
                k_short += 1
            else:
                k_above_n2 += 1
            if mn > thresh_hi:
                k_above_nsq4 += 1

        print(f"  Over all {N} keys:")
        print(f"  {'':4} {'min-cycle':>12} {'max-cycle':>12} {'num-cycles':>12}")
        print(f"  {'min over K':>14} {min(all_min):>12} {min(all_max):>12} {min(ncyc):>12}")
        print(f"  {'mean over K':>14} {sum(all_min)/N:>12.2f} {sum(all_max)/N:>12.2f} {sum(ncyc)/N:>12.2f}")
        print(f"  {'max over K':>14} {max(all_min):>12} {max(all_max):>12} {max(ncyc):>12}")
        print()
        print(f"  K with single cycle (period = {N}):       {k_full:>4} / {N}  ({100*k_full/N:.1f}%)")
        print(f"  K with min cycle <= n/2 = {n//2} (degenerate): {k_short:>4} / {N}  ({100*k_short/N:.1f}%)")
        print(f"  K with min cycle >  n/2 = {n//2}:               {k_above_n2:>4} / {N}  ({100*k_above_n2/N:.1f}%)")
        print(f"  K with min cycle > n²/4 = {thresh_hi}:            {k_above_nsq4:>4} / {N}  ({100*k_above_nsq4/N:.1f}%)")
        print()


# ─── §2: Sampled orbit-length distribution at n = 8, 12, 16 ─────────────────

def section2():
    print(SEP)
    print("§2 — Sampled Orbit-Length Distribution at n = 8, 12, 16")
    print(SEP)
    print("  Random (K, G) pairs, K != 0.  Orbit length via Brent's (exact, no cap).")
    print()

    for n, n_samples in [(8, 2000), (12, 1000), (16, 400)]:
        mask = (1 << n) - 1
        cap  = 1 << n          # exact — no orbit can exceed 2^n
        lengths = []
        for _ in range(n_samples):
            K = random.randint(1, mask)
            G = random.randint(0, mask)
            L, _ = orbit_brent(G, K, n, cap)
            lengths.append(L)
        lengths.sort()

        mn   = lengths[0]
        mx   = lengths[-1]
        mean = sum(lengths) / len(lengths)
        med  = lengths[len(lengths) // 2]
        p10  = lengths[int(0.10 * len(lengths))]
        p90  = lengths[int(0.90 * len(lengths))]

        def lg(v): return math.log2(v) if v > 0 else 0

        print(f"  n={n},  {n_samples} samples:")
        print(f"    min={mn}  p10={p10}  median={med}  mean={mean:.0f}  p90={p90}  max={mx}")
        print(f"    (log2: min={lg(mn):.2f}  median={lg(med):.2f}  mean={lg(mean):.2f}  max={lg(mx):.2f})")

        # Distribution by power-of-two bucket
        buckets: dict = {}
        for L in lengths:
            b = max(0, int(lg(L)))
            buckets[b] = buckets.get(b, 0) + 1
        print(f"    Distribution by power-of-2 bucket (each █ = {n_samples//50}):")
        for b in sorted(buckets):
            bar = "█" * max(1, buckets[b] * 50 // n_samples) if buckets[b] else ""
            print(f"      [2^{b:<2}..2^{b+1}) {buckets[b]:>5}  {bar}")

        # Fraction with orbit length > N/4, N/2, N
        N = 1 << n
        above_q = sum(1 for L in lengths if L >  N // 4) / len(lengths)
        above_h = sum(1 for L in lengths if L >  N // 2) / len(lengths)
        above_f = sum(1 for L in lengths if L == N)       / len(lengths)
        print(f"    orbit > N/4: {100*above_q:.1f}%   orbit > N/2: {100*above_h:.1f}%   orbit = N (full): {100*above_f:.1f}%")
        print()


# ─── §3: Non-commutativity verification ──────────────────────────────────────

def section3():
    print(SEP)
    print("§3 — Non-Commutativity Verification (Theorem 15 Empirical Check)")
    print(SEP)
    print("  Theorem 15: {pi_K} is a non-abelian family — pi_{K1} o pi_{K2} != pi_{K2} o pi_{K1}")
    print("  for generic K1 != K2.")
    print("  Test: for random (K1 != K2, A), check pi_{K1}(pi_{K2}(A)) != pi_{K2}(pi_{K1}(A)).")
    print()

    for n in [8, 16, 32]:
        mask = (1 << n) - 1
        trials = 40_000
        comm = 0      # compositions agree (commuting point)
        non_comm = 0  # compositions differ
        for _ in range(trials):
            K1 = random.randint(1, mask)
            K2 = random.randint(1, mask)
            while K2 == K1:
                K2 = random.randint(1, mask)
            A = random.randint(0, mask)
            lhs = pi_K(pi_K(A, K1, n), K2, n)   # pi_{K2} o pi_{K1}
            rhs = pi_K(pi_K(A, K2, n), K1, n)   # pi_{K1} o pi_{K2}
            if lhs == rhs:
                comm += 1
            else:
                non_comm += 1
        rate = 100 * non_comm / trials
        print(f"  n={n:>2}:  {non_comm}/{trials} triples non-commuting  ({rate:.2f}%)")
        if comm:
            print(f"         {comm} commuting points found (may be coincidental point agreements,")
            print(f"         not evidence that the pair commutes as a permutation)")
    print()
    print("  Commuting point != commuting permutation: two non-commuting permutations can")
    print("  agree on isolated points by coincidence.  For Theorem 15, the relevant")
    print("  criterion is whether pi_{K1} o pi_{K2} = pi_{K2} o pi_{K1} as functions.")
    print()

    # For n=8: check full permutation commutativity (all 256 points must agree)
    n = 8; N = 1 << n; mask = N - 1
    trials_full = 1000
    full_comm = 0
    for _ in range(trials_full):
        K1 = random.randint(1, mask)
        K2 = random.randint(1, mask)
        while K2 == K1:
            K2 = random.randint(1, mask)
        if all(pi_K(pi_K(A, K1, n), K2, n) == pi_K(pi_K(A, K2, n), K1, n)
               for A in range(N)):
            full_comm += 1
    print(f"  n=8 full-permutation commutativity: {full_comm}/{trials_full} pairs commute  ({100*full_comm/trials_full:.1f}%)")
    print(f"  (Pairs where pi_{{K1}} o pi_{{K2}} == pi_{{K2}} o pi_{{K1}} for ALL A in {{0..255}})")


# ─── §4: Orbit lower bounds at large n ───────────────────────────────────────

def section4():
    print(SEP)
    print("§4 — Orbit Lower Bounds at Large n  (cap = 2^16 = 65 536)")
    print(SEP)
    cap = 1 << 16
    print(f"  Brent's algorithm with step cap {cap} (2^16).")
    print(f"  'exceeded' = orbit length > {cap}; K=0 excluded in all tests.")
    print()

    params = [(24, 40, 5), (32, 40, 5)]
    if FULL_ORBIT_SWEEP:
        params = [(24, 200, 10), (32, 200, 10)]

    for n, n_K, n_G in params:
        mask = (1 << n) - 1
        exceeded = 0; short = []
        total = n_K * n_G
        for _ in range(n_K):
            K = random.randint(1, mask)
            for _ in range(n_G):
                G = random.randint(0, mask)
                L, capped = orbit_brent(G, K, n, cap)
                if capped:
                    exceeded += 1
                else:
                    short.append(L)
        pct = 100 * exceeded / total
        print(f"  n={n}: {exceeded}/{total} pairs exceeded cap (orbit > 2^16) = {pct:.1f}%")
        if short:
            print(f"         Short orbits found: n={len(short)}, lengths = {sorted(short)[:10]}")
        else:
            print(f"         No short orbits found  (all {total} pairs have orbit > 2^16)")
        print()

    if FULL_ORBIT_SWEEP:
        # Higher cap sweep for confirmation
        cap2 = 1 << 20
        print(f"  Extended sweep (FULL_ORBIT_SWEEP): cap = 2^20 = {cap2}")
        for n, n_K, n_G in [(32, 50, 5)]:
            mask = (1 << n) - 1
            exceeded = 0; short = []
            total = n_K * n_G
            for _ in range(n_K):
                K = random.randint(1, mask)
                for _ in range(n_G):
                    G = random.randint(0, mask)
                    L, capped = orbit_brent(G, K, n, cap2)
                    if capped:
                        exceeded += 1
                    else:
                        short.append(L)
            pct = 100 * exceeded / total
            print(f"  n={n}: {exceeded}/{total} pairs exceeded 2^20 cap = {pct:.1f}%")
            if short:
                print(f"         Short orbits found: lengths = {sorted(short)[:5]}")
            print()

    print("  NON-MONOTONE BEHAVIOUR (key finding):")
    print("  n=24 has anomalously SHORT orbits (typical length 7–27) despite a 2^24 state")
    print("  space.  n=32 has all orbits > 2^16.  Orbit length is NOT monotone in n.")
    print("  This non-monotone behaviour may be caused by arithmetic resonance between M's")
    print("  period (n/2) and the delta function's additive offset at composite n=24=8x3.")
    print("  Implication: production security (n=256) requires independent analysis;")
    print("  extrapolating from n=32 alone is not safe.")


# ─── §5: CSP attack feasibility at n = 6, 8 ──────────────────────────────────

def section5():
    print(SEP)
    print("§5 — CSP Attack Feasibility at n = 6, 8 (Exhaustive Brute-Force)")
    print(SEP)
    print("  Construction: C = pi_{K1}(pi_{K2}(pi_{K1}^{-1}(G)))")
    print("  Attack: given (G, K2, C), find all K1 in {1,...,2^n-1} satisfying equation.")
    print("  K1=0 excluded (degenerate).")
    print()

    for n in [6, 8]:
        N = 1 << n
        G = N // 3             # arbitrary fixed public base

        n_trials = 300 if n == 6 else 200
        sol_counts = []
        unique_trials = 0

        for _ in range(n_trials):
            K1 = random.randint(1, N - 1)
            K2 = random.randint(1, N - 1)
            while K2 == K1:
                K2 = random.randint(1, N - 1)

            # Compute C = pi_{K1}(pi_{K2}(pi_{K1}^{-1}(G)))
            inner  = pi_K_inv(G, K1, n)
            middle = pi_K(inner, K2, n)
            C      = pi_K(middle, K1, n)

            # Brute-force: all candidate K1' values
            hits = 0
            for K1p in range(1, N):
                inner_p  = pi_K_inv(G, K1p, n)
                middle_p = pi_K(inner_p, K2, n)
                Cp       = pi_K(middle_p, K1p, n)
                if Cp == C:
                    hits += 1
            sol_counts.append(hits)
            if hits == 1:
                unique_trials += 1

        zero  = sol_counts.count(0)
        one   = sol_counts.count(1)
        multi = sum(1 for s in sol_counts if s > 1)
        avg   = sum(sol_counts) / len(sol_counts)
        max_s = max(sol_counts)

        print(f"  n={n}  (key space {N-1}, {n_trials} random (K1 != K2) trials, G={G}):")
        print(f"    Solutions per trial: avg={avg:.2f}  max={max_s}")
        print(f"    0 solutions (bug): {zero}   1 solution (unique): {one}   >1 solutions: {multi}")
        print(f"    Unique-solution rate: {100*unique_trials/n_trials:.1f}%")
        if multi > 0:
            extras = [s for s in sol_counts if s > 1]
            print(f"    Multi-solution counts (sample): {sorted(extras)[:10]}")
        print()

    print("  A unique solution means the CSP has effectively one answer in this space.")
    print("  Multiple solutions occur when distinct K1 values produce the same (G,K2,C)")
    print("  triple — an algebraic collision in the conjugation map.")
    print("  At production bit-sizes (n=256), brute-force is infeasible regardless.")


# ─── §6: Summary and protocol implications ────────────────────────────────────

def section6():
    print(SEP)
    print("§6 — Protocol Implications for §11.8.5 Obstacle 2")
    print(SEP)
    print()
    print("  WHAT THIS SCRIPT ADDRESSES:")
    print("  Obstacle 2 from §11.8.5: 'no verified lower bound on orbit lengths of pi_K.'")
    print()
    print("  EMPIRICAL FINDINGS SUMMARY:")
    print("  1. K=0 is degenerate — pi_0 = M is GF(2)-linear, all orbits divide n/2.")
    print("     Any NASG deployment MUST validate K != 0 (and K not rotation-periodic).")
    print("  2. Orbit length is NON-MONOTONE in n (see §4): n=24 shows anomalously short")
    print("     orbits (7–27) while n=32 shows all orbits > 2^16.  The non-monotone jump")
    print("     rules out any simple 'orbit grows with n' extrapolation to n=256.")
    print("  3. At n=32: all sampled (K, G) pairs have orbit > 2^16 >> n^3 = 32768.")
    print("     Empirical lower bound for n=32: orbit >= 2^16 for generic K != 0.")
    print("  4. The permutation family is non-abelian for >= 99% of random (K1, K2) pairs,")
    print("     confirming Theorem 15 and the CSP-hardness prerequisite.")
    print("  5. Brute-force CSP recovery at small n yields ~2 solutions per (G, K2, C)")
    print("     triple (33–35% unique-solution rate), indicating a 2-fold algebraic")
    print("     collision rate at small n.  Production bit-size is infeasible to check.")
    print()
    print("  OBSTACLE 2 STATUS:")
    print("  PARTIALLY addressed: orbit > 2^16 confirmed empirically at n=32, but")
    print("  the n=24 anomaly (all orbits short) shows orbit length is not monotone in n.")
    print("  Production security (n=256) is uncharacterised and cannot be inferred")
    print("  from n=32 alone.  A formal proof — |<pi_K>| >= Omega(2^{cn}) for all K != 0")
    print("  — remains open and is the prerequisite for removing obstacle 2.")
    print()
    print("  REMAINING OPEN OBSTACLES (from §11.8.5):")
    print("  1. No transfer theorem from black-box CSP hardness to the explicit NL-FSCX v2")
    print("     circuit model.  An algebraic attacker may exploit the carry structure of F2")
    print("     directly without treating pi_K as a black box.")
    print("  3. No formal reduction to a studied CSP instance (braid group results do not")
    print("     transfer to permutation groups generated by NL-FSCX v2 without a dedicated")
    print("     algebraic reduction).")
    print()
    print("  PROTOCOL READINESS: NASG (Option C) remains a RESEARCH PROTOTYPE.")
    print("  Obstacles 1 and 3 block production deployment regardless of obstacle 2 status.")
    print("  The empirical orbit-length lower bound from this script supports continued")
    print("  research into NASG but does not constitute a security proof.")


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    print()
    print("nl_fscx_v2_orbit.py — NL-FSCX v2 orbit-length analysis (TODO #78.E)")
    if FULL_ORBIT_SWEEP:
        print("  (FULL_ORBIT_SWEEP = True — extended large-n sweep enabled)")
    print()
    t0 = time.monotonic()
    section1(); print(); sys.stdout.flush()
    section2(); print(); sys.stdout.flush()
    section3(); print(); sys.stdout.flush()
    section4(); print(); sys.stdout.flush()
    section5(); print(); sys.stdout.flush()
    section6()
    print()
    print(SEP)
    print(f"Total runtime: {time.monotonic() - t0:.1f} s")
    print("END nl_fscx_v2_orbit.py")
    print(SEP)


if __name__ == '__main__':
    main()
