package herradurakex;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/** GENERATED by spec/generate_spec.py (TODO #274) -- DO NOT EDIT.
 *  Regenerate with `python3 spec/generate_spec.py`; `--check` fails if this file is stale. */
final class CliFlagTable {
    private CliFlagTable() { }

    static final Map<String, Set<String>> FLAGS;

    static {
        Map<String, Set<String>> m = new HashMap<>();
        m.put("cred-issue", new HashSet<>(Arrays.asList("in", "our", "out", "rounds")));
        m.put("cred-prove", new HashSet<>(Arrays.asList("in", "msg", "out", "rounds")));
        m.put("cred-verify", new HashSet<>(Arrays.asList("cred", "issuer", "msg", "proof", "pubkey")));
        m.put("dec", new HashSet<>(Arrays.asList("ad", "algo", "in", "key", "out")));
        m.put("decfile", new HashSet<>(Arrays.asList("algo", "in", "key", "out")));
        m.put("dgst", new HashSet<>(Arrays.asList("algo", "in", "out")));
        m.put("enc", new HashSet<>(Arrays.asList("ad", "aead", "algo", "in", "key", "out", "pubkey")));
        m.put("encfile", new HashSet<>(Arrays.asList("algo", "in", "key", "out")));
        m.put("fpe", new HashSet<>(Arrays.asList("context", "decrypt", "encrypt", "in", "key", "out", "v3")));
        m.put("genpkey", new HashSet<>(Arrays.asList("algo", "bits", "out", "xmss-height")));
        m.put("kex", new HashSet<>(Arrays.asList("algo", "kdf", "our", "our-kem", "out", "their", "their-kem")));
        m.put("oprf-blind", new HashSet<>(Arrays.asList("in", "out")));
        m.put("oprf-eval", new HashSet<>(Arrays.asList("in", "key", "out")));
        m.put("oprf-unblind", new HashSet<>(Arrays.asList("eval", "out", "state")));
        m.put("pake-demo", new HashSet<>(Arrays.asList("key", "password", "username")));
        m.put("pake-register", new HashSet<>(Arrays.asList("key", "out", "password", "username")));
        m.put("pkey", new HashSet<>(Arrays.asList("in", "out", "pubout", "text")));
        m.put("rand", new HashSet<>(Arrays.asList("bytes", "hex", "out", "personalization", "reseed", "seed", "state")));
        m.put("sign", new HashSet<>(Arrays.asList("algo", "digest", "in", "key", "out", "ring", "rounds")));
        m.put("threshold-aggregate", new HashSet<>(Arrays.asList("commit", "commits", "digest", "in", "out")));
        m.put("threshold-combine", new HashSet<>(Arrays.asList("aggregate", "out", "partial", "partials")));
        m.put("threshold-commit", new HashSet<>(Arrays.asList("commit-out", "key", "nonce-out")));
        m.put("threshold-respond", new HashSet<>(Arrays.asList("aggregate", "commit", "commits", "key", "nonce", "out")));
        m.put("twk", new HashSet<>(Arrays.asList("bidx", "decrypt", "encrypt", "in", "key", "out", "sector", "v3")));
        m.put("verify", new HashSet<>(Arrays.asList("algo", "digest", "in", "pubkey", "ring", "sig")));
        FLAGS = Collections.unmodifiableMap(m);
    }
}
