/* GENERATED by spec/generate_spec.py (TODO #274) -- DO NOT EDIT.
 * Regenerate with `python3 spec/generate_spec.py`; `--check` fails if this file is stale. */
#ifndef HKX_CLI_FLAG_TABLE_H
#define HKX_CLI_FLAG_TABLE_H

static const char *const hkx_flags_cred_issue[] = {"--in", "--our", "--out", "--rounds"};
static const char *const hkx_valued_cred_issue[] = {"--in", "--our", "--out", "--rounds"};
static const char *const hkx_flags_cred_prove[] = {"--in", "--msg", "--out", "--rounds"};
static const char *const hkx_valued_cred_prove[] = {"--in", "--msg", "--out", "--rounds"};
static const char *const hkx_flags_cred_verify[] = {"--cred", "--issuer", "--msg", "--proof", "--pubkey", "--rounds"};
static const char *const hkx_valued_cred_verify[] = {"--cred", "--issuer", "--msg", "--proof", "--pubkey", "--rounds"};
static const char *const hkx_flags_dec[] = {"--ad", "--algo", "--in", "--key", "--out"};
static const char *const hkx_valued_dec[] = {"--ad", "--algo", "--in", "--key", "--out"};
static const char *const hkx_flags_decfile[] = {"--algo", "--in", "--key", "--out"};
static const char *const hkx_valued_decfile[] = {"--algo", "--in", "--key", "--out"};
static const char *const hkx_flags_dgst[] = {"--algo", "--in", "--out"};
static const char *const hkx_valued_dgst[] = {"--algo", "--in", "--out"};
static const char *const hkx_flags_enc[] = {"--ad", "--aead", "--algo", "--in", "--key", "--out", "--pubkey"};
static const char *const hkx_valued_enc[] = {"--ad", "--algo", "--in", "--key", "--out", "--pubkey"};
static const char *const hkx_flags_encfile[] = {"--algo", "--in", "--key", "--out"};
static const char *const hkx_valued_encfile[] = {"--algo", "--in", "--key", "--out"};
static const char *const hkx_flags_fpe[] = {"--context", "--decrypt", "--encrypt", "--in", "--key", "--out", "--v3"};
static const char *const hkx_valued_fpe[] = {"--context", "--in", "--key", "--out"};
static const char *const hkx_flags_genpkey[] = {"--algo", "--kdf-iterations", "--out", "--passphrase", "--xmss-height"};
static const char *const hkx_valued_genpkey[] = {"--algo", "--kdf-iterations", "--out", "--passphrase", "--xmss-height"};
static const char *const hkx_flags_kex[] = {"--algo", "--kdf", "--our", "--our-kem", "--out", "--their", "--their-kem"};
static const char *const hkx_valued_kex[] = {"--algo", "--kdf", "--our", "--our-kem", "--out", "--their", "--their-kem"};
static const char *const hkx_flags_oprf_blind[] = {"--in", "--out"};
static const char *const hkx_valued_oprf_blind[] = {"--in", "--out"};
static const char *const hkx_flags_oprf_eval[] = {"--in", "--key", "--out"};
static const char *const hkx_valued_oprf_eval[] = {"--in", "--key", "--out"};
static const char *const hkx_flags_oprf_unblind[] = {"--eval", "--out", "--state"};
static const char *const hkx_valued_oprf_unblind[] = {"--eval", "--out", "--state"};
static const char *const hkx_flags_pake_demo[] = {"--key", "--password"};
static const char *const hkx_valued_pake_demo[] = {"--key", "--password"};
static const char *const hkx_flags_pake_register[] = {"--key", "--out", "--password"};
static const char *const hkx_valued_pake_register[] = {"--key", "--out", "--password"};
static const char *const hkx_flags_pkey[] = {"--decrypt", "--in", "--out", "--passphrase", "--pubout", "--text"};
static const char *const hkx_valued_pkey[] = {"--in", "--out", "--passphrase"};
static const char *const hkx_flags_rand[] = {"--bytes", "--hex", "--out", "--personalization", "--reseed", "--seed", "--state"};
static const char *const hkx_valued_rand[] = {"--bytes", "--out", "--personalization", "--reseed", "--seed", "--state"};
static const char *const hkx_flags_sign[] = {"--algo", "--digest", "--in", "--key", "--out", "--ring", "--rounds"};
static const char *const hkx_valued_sign[] = {"--algo", "--digest", "--in", "--key", "--out", "--ring", "--rounds"};
static const char *const hkx_flags_threshold_aggregate[] = {"--commit", "--commits", "--digest", "--in", "--out"};
static const char *const hkx_valued_threshold_aggregate[] = {"--commit", "--commits", "--digest", "--in", "--out"};
static const char *const hkx_flags_threshold_combine[] = {"--aggregate", "--out", "--partial", "--partials"};
static const char *const hkx_valued_threshold_combine[] = {"--aggregate", "--out", "--partial", "--partials"};
static const char *const hkx_flags_threshold_commit[] = {"--commit-out", "--key", "--nonce-out"};
static const char *const hkx_valued_threshold_commit[] = {"--commit-out", "--key", "--nonce-out"};
static const char *const hkx_flags_threshold_respond[] = {"--aggregate", "--commit", "--commits", "--key", "--nonce", "--out"};
static const char *const hkx_valued_threshold_respond[] = {"--aggregate", "--commit", "--commits", "--key", "--nonce", "--out"};
static const char *const hkx_flags_twk[] = {"--bidx", "--decrypt", "--encrypt", "--in", "--key", "--out", "--sector", "--v3"};
static const char *const hkx_valued_twk[] = {"--bidx", "--in", "--key", "--out", "--sector"};
static const char *const hkx_flags_verify[] = {"--algo", "--digest", "--in", "--pubkey", "--ring", "--sig"};
static const char *const hkx_valued_verify[] = {"--algo", "--digest", "--in", "--pubkey", "--ring", "--sig"};

typedef struct { const char *cmd; const char *const *flags; int n;
                 const char *const *valued; int nv; } HkxFlagSet;

static const HkxFlagSet HKX_FLAG_SETS[] = {
    {"cred-issue", hkx_flags_cred_issue, 4, hkx_valued_cred_issue, 4},
    {"cred-prove", hkx_flags_cred_prove, 4, hkx_valued_cred_prove, 4},
    {"cred-verify", hkx_flags_cred_verify, 6, hkx_valued_cred_verify, 6},
    {"dec", hkx_flags_dec, 5, hkx_valued_dec, 5},
    {"decfile", hkx_flags_decfile, 4, hkx_valued_decfile, 4},
    {"dgst", hkx_flags_dgst, 3, hkx_valued_dgst, 3},
    {"enc", hkx_flags_enc, 7, hkx_valued_enc, 6},
    {"encfile", hkx_flags_encfile, 4, hkx_valued_encfile, 4},
    {"fpe", hkx_flags_fpe, 7, hkx_valued_fpe, 4},
    {"genpkey", hkx_flags_genpkey, 5, hkx_valued_genpkey, 5},
    {"kex", hkx_flags_kex, 7, hkx_valued_kex, 7},
    {"oprf-blind", hkx_flags_oprf_blind, 2, hkx_valued_oprf_blind, 2},
    {"oprf-eval", hkx_flags_oprf_eval, 3, hkx_valued_oprf_eval, 3},
    {"oprf-unblind", hkx_flags_oprf_unblind, 3, hkx_valued_oprf_unblind, 3},
    {"pake-demo", hkx_flags_pake_demo, 2, hkx_valued_pake_demo, 2},
    {"pake-register", hkx_flags_pake_register, 3, hkx_valued_pake_register, 3},
    {"pkey", hkx_flags_pkey, 6, hkx_valued_pkey, 3},
    {"rand", hkx_flags_rand, 7, hkx_valued_rand, 6},
    {"sign", hkx_flags_sign, 7, hkx_valued_sign, 7},
    {"threshold-aggregate", hkx_flags_threshold_aggregate, 5, hkx_valued_threshold_aggregate, 5},
    {"threshold-combine", hkx_flags_threshold_combine, 4, hkx_valued_threshold_combine, 4},
    {"threshold-commit", hkx_flags_threshold_commit, 3, hkx_valued_threshold_commit, 3},
    {"threshold-respond", hkx_flags_threshold_respond, 6, hkx_valued_threshold_respond, 6},
    {"twk", hkx_flags_twk, 8, hkx_valued_twk, 5},
    {"verify", hkx_flags_verify, 6, hkx_valued_verify, 6},
};
static const int HKX_FLAG_SETS_N = (int)(sizeof(HKX_FLAG_SETS) / sizeof(HKX_FLAG_SETS[0]));

#endif /* HKX_CLI_FLAG_TABLE_H */
