#!/usr/bin/env bash
# CliTest/test_cred_interop.sh — C↔Python HCRED cross-language interop (n=256)
# Keys generated by one implementation are proved/verified by the other.
set -euo pipefail

CLI_C="$(dirname "$0")/../HerraduraCli/herradura_cli"
CLI_PY="python3 $(dirname "$0")/../HerraduraCli/herradura.py"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
PASS=0; FAIL=0

check() {
    local label="$1"; shift
    local output rc
    output=$("$@" 2>&1) && rc=0 || rc=$?
    if [ "$rc" -eq 0 ]; then
        echo "PASS $label"
        PASS=$((PASS+1))
    else
        echo "FAIL $label (rc=$rc): $output"
        FAIL=$((FAIL+1))
    fi
}

check_fail() {
    local label="$1"; shift
    local output rc
    output=$("$@" 2>&1) && rc=0 || rc=$?
    if [ "$rc" -ne 0 ]; then
        echo "PASS $label (rejected as expected)"
        PASS=$((PASS+1))
    else
        echo "FAIL $label: expected rejection but got rc=0"
        FAIL=$((FAIL+1))
    fi
}

# ── C-generated user key, Python-generated user key (both n=256) ───────────
"$CLI_C" genpkey --algo hcred      --out "$TMP/c_user.pem"  2>/dev/null
"$CLI_C" pkey    --pubout --in "$TMP/c_user.pem" --out "$TMP/c_user_pub.pem"
$CLI_PY  genpkey --algo hcred --bits 256 --out "$TMP/py_user.pem" 2>/dev/null
$CLI_PY  pkey    --pubout --in "$TMP/py_user.pem" --out "$TMP/py_user_pub.pem"

# Issuer keys
"$CLI_C" genpkey --algo hpks-stern --out "$TMP/c_issuer.pem"  2>/dev/null
"$CLI_C" pkey    --pubout --in "$TMP/c_issuer.pem" --out "$TMP/c_issuer_pub.pem"
$CLI_PY  genpkey --algo hpks-stern --out "$TMP/py_issuer.pem" 2>/dev/null
$CLI_PY  pkey    --pubout --in "$TMP/py_issuer.pem" --out "$TMP/py_issuer_pub.pem"

# ── Proofs ──────────────────────────────────────────────────────────────────
"$CLI_C" cred-prove --in "$TMP/c_user.pem"  --msg "interop" --rounds 4 \
                    --out "$TMP/c_proof.pem" 2>/dev/null
$CLI_PY  cred-prove --in "$TMP/py_user.pem" --msg "interop" --rounds 4 \
                    --out "$TMP/py_proof.pem" 2>/dev/null

# C prove → C verify
check "C prove → C verify"  \
    "$CLI_C" cred-verify --proof "$TMP/c_proof.pem" \
    --pubkey "$TMP/c_user_pub.pem" --msg "interop"

# C prove → Python verify
check "C prove → Py verify" \
    $CLI_PY cred-verify --proof "$TMP/c_proof.pem" \
    --pubkey "$TMP/c_user_pub.pem" --msg "interop"

# Python prove → C verify
check "Py prove → C verify" \
    "$CLI_C" cred-verify --proof "$TMP/py_proof.pem" \
    --pubkey "$TMP/py_user_pub.pem" --msg "interop"

# Python prove → Python verify
check "Py prove → Py verify" \
    $CLI_PY cred-verify --proof "$TMP/py_proof.pem" \
    --pubkey "$TMP/py_user_pub.pem" --msg "interop"

# ── Credential interop ──────────────────────────────────────────────────────
# C issuer signs C user key
"$CLI_C" cred-issue --our "$TMP/c_issuer.pem" --in "$TMP/c_user_pub.pem" \
                    --out "$TMP/c2c_cred.pem" 2>/dev/null
# Python issuer signs C user key — must match C's SDF_ROUNDS=32 for interop
$CLI_PY  cred-issue --our "$TMP/py_issuer.pem" --in "$TMP/c_user_pub.pem" \
                    --rounds 32 --out "$TMP/py2c_cred.pem" 2>/dev/null

check "C cred → C verify"  \
    "$CLI_C" cred-verify --proof "$TMP/c_proof.pem" \
    --pubkey "$TMP/c_user_pub.pem" --msg "interop" \
    --cred "$TMP/c2c_cred.pem" --issuer "$TMP/c_issuer_pub.pem"

check "C cred → Py verify" \
    $CLI_PY cred-verify --proof "$TMP/c_proof.pem" \
    --pubkey "$TMP/c_user_pub.pem" --msg "interop" \
    --cred "$TMP/c2c_cred.pem" --issuer "$TMP/c_issuer_pub.pem"

check "Py cred → C verify" \
    "$CLI_C" cred-verify --proof "$TMP/c_proof.pem" \
    --pubkey "$TMP/c_user_pub.pem" --msg "interop" \
    --cred "$TMP/py2c_cred.pem" --issuer "$TMP/py_issuer_pub.pem"

check "Py cred → Py verify" \
    $CLI_PY cred-verify --proof "$TMP/c_proof.pem" \
    --pubkey "$TMP/c_user_pub.pem" --msg "interop" \
    --cred "$TMP/py2c_cred.pem" --issuer "$TMP/py_issuer_pub.pem"

# Wrong-message rejection
check_fail "wrong-msg reject (C verifier)" \
    "$CLI_C" cred-verify --proof "$TMP/c_proof.pem" \
    --pubkey "$TMP/c_user_pub.pem" --msg "wrong"

check_fail "wrong-msg reject (Py verifier)" \
    $CLI_PY cred-verify --proof "$TMP/c_proof.pem" \
    --pubkey "$TMP/c_user_pub.pem" --msg "wrong"

# ── Summary ────────────────────────────────────────────────────────────────
echo ""
echo "Results: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ]
