#!/usr/bin/env bash
# CliTest/test_cred_interop.sh — C↔Python↔Go HCRED cross-language interop (n=256)
# Keys generated by one implementation are proved/verified by the others.
set -euo pipefail

CLI_C="$(dirname "$0")/../HerraduraCli/herradura_cli"
CLI_PY="python3 $(dirname "$0")/../HerraduraCli/herradura.py"
CLI_GO="$(dirname "$0")/../HerraduraCli/herradura_cli_go"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
PASS=0; FAIL=0
HAVE_GO=1
if [ ! -x "$CLI_GO" ]; then
    echo "SKIP: Go CLI not found at $CLI_GO (run build_go.sh first) — Go coverage will be skipped"
    HAVE_GO=0
fi

check() {
    local label="$1"; shift
    local output rc
    output=$("$@" 2>&1) && rc=0 || rc=$?
    if [ "$rc" -eq 0 ]; then
        echo "PASS $label"
        PASS=$((PASS+1))
    else
        echo "FAIL $label (rc=$rc): $output"
        FAIL=$((FAIL+1))
    fi
}

check_fail() {
    local label="$1"; shift
    local output rc
    output=$("$@" 2>&1) && rc=0 || rc=$?
    if [ "$rc" -ne 0 ]; then
        echo "PASS $label (rejected as expected)"
        PASS=$((PASS+1))
    else
        echo "FAIL $label: expected rejection but got rc=0"
        FAIL=$((FAIL+1))
    fi
}

# ── C-generated, Python-generated, Go-generated user keys (all n=256) ──────
"$CLI_C" genpkey --algo hcred      --out "$TMP/c_user.pem"  2>/dev/null
"$CLI_C" pkey    --pubout --in "$TMP/c_user.pem" --out "$TMP/c_user_pub.pem"
$CLI_PY  genpkey --algo hcred --bits 256 --out "$TMP/py_user.pem" 2>/dev/null
$CLI_PY  pkey    --pubout --in "$TMP/py_user.pem" --out "$TMP/py_user_pub.pem"

# Issuer keys
"$CLI_C" genpkey --algo hpks-stern --out "$TMP/c_issuer.pem"  2>/dev/null
"$CLI_C" pkey    --pubout --in "$TMP/c_issuer.pem" --out "$TMP/c_issuer_pub.pem"
$CLI_PY  genpkey --algo hpks-stern --out "$TMP/py_issuer.pem" 2>/dev/null
$CLI_PY  pkey    --pubout --in "$TMP/py_issuer.pem" --out "$TMP/py_issuer_pub.pem"

if [ "$HAVE_GO" -eq 1 ]; then
    "$CLI_GO" genpkey --algo hcred --bits 256 --out "$TMP/go_user.pem" 2>/dev/null
    "$CLI_GO" pkey    --pubout --in "$TMP/go_user.pem" --out "$TMP/go_user_pub.pem"
    "$CLI_GO" genpkey --algo hpks-stern --out "$TMP/go_issuer.pem" 2>/dev/null
    "$CLI_GO" pkey    --pubout --in "$TMP/go_issuer.pem" --out "$TMP/go_issuer_pub.pem"
fi

# ── Proofs ──────────────────────────────────────────────────────────────────
"$CLI_C" cred-prove --in "$TMP/c_user.pem"  --msg "interop" --rounds 16 \
                    --out "$TMP/c_proof.pem" 2>/dev/null
$CLI_PY  cred-prove --in "$TMP/py_user.pem" --msg "interop" --rounds 16 \
                    --out "$TMP/py_proof.pem" 2>/dev/null
if [ "$HAVE_GO" -eq 1 ]; then
    "$CLI_GO" cred-prove --in "$TMP/go_user.pem" --msg "interop" --rounds 16 \
                    --out "$TMP/go_proof.pem" 2>/dev/null
fi

# C prove → C verify
check "C prove → C verify"  \
    "$CLI_C" cred-verify --proof "$TMP/c_proof.pem" \
    --pubkey "$TMP/c_user_pub.pem" --msg "interop"

# C prove → Python verify
check "C prove → Py verify" \
    $CLI_PY cred-verify --proof "$TMP/c_proof.pem" \
    --pubkey "$TMP/c_user_pub.pem" --msg "interop"

# Python prove → C verify
check "Py prove → C verify" \
    "$CLI_C" cred-verify --proof "$TMP/py_proof.pem" \
    --pubkey "$TMP/py_user_pub.pem" --msg "interop"

# Python prove → Python verify
check "Py prove → Py verify" \
    $CLI_PY cred-verify --proof "$TMP/py_proof.pem" \
    --pubkey "$TMP/py_user_pub.pem" --msg "interop"

if [ "$HAVE_GO" -eq 1 ]; then
    # Go prove → Go verify
    check "Go prove → Go verify" \
        "$CLI_GO" cred-verify --proof "$TMP/go_proof.pem" \
        --pubkey "$TMP/go_user_pub.pem" --msg "interop"

    # Go prove → C verify, Go prove → Py verify
    check "Go prove → C verify" \
        "$CLI_C" cred-verify --proof "$TMP/go_proof.pem" \
        --pubkey "$TMP/go_user_pub.pem" --msg "interop"
    check "Go prove → Py verify" \
        $CLI_PY cred-verify --proof "$TMP/go_proof.pem" \
        --pubkey "$TMP/go_user_pub.pem" --msg "interop"

    # C prove → Go verify, Py prove → Go verify
    check "C prove → Go verify" \
        "$CLI_GO" cred-verify --proof "$TMP/c_proof.pem" \
        --pubkey "$TMP/c_user_pub.pem" --msg "interop"
    check "Py prove → Go verify" \
        "$CLI_GO" cred-verify --proof "$TMP/py_proof.pem" \
        --pubkey "$TMP/py_user_pub.pem" --msg "interop"
fi

# ── Credential interop ──────────────────────────────────────────────────────
# C issuer signs C user key
"$CLI_C" cred-issue --our "$TMP/c_issuer.pem" --in "$TMP/c_user_pub.pem" \
                    --out "$TMP/c2c_cred.pem" 2>/dev/null
# Python issuer signs C user key at Python's own 219-round default.  Before
# TODO #236 this needed an explicit --rounds 32 to match C's compile-time
# SDF_ROUNDS, which meant cross-language HCRED interop was only ever exercised
# at (2/3)^32 soundness.  C's reader now takes the round count from the PEM.
$CLI_PY  cred-issue --our "$TMP/py_issuer.pem" --in "$TMP/c_user_pub.pem" \
                    --out "$TMP/py2c_cred.pem" 2>/dev/null

check "C cred → C verify"  \
    "$CLI_C" cred-verify --proof "$TMP/c_proof.pem" \
    --pubkey "$TMP/c_user_pub.pem" --msg "interop" \
    --cred "$TMP/c2c_cred.pem" --issuer "$TMP/c_issuer_pub.pem"

check "C cred → Py verify" \
    $CLI_PY cred-verify --proof "$TMP/c_proof.pem" \
    --pubkey "$TMP/c_user_pub.pem" --msg "interop" \
    --cred "$TMP/c2c_cred.pem" --issuer "$TMP/c_issuer_pub.pem"

check "Py cred → C verify" \
    "$CLI_C" cred-verify --proof "$TMP/c_proof.pem" \
    --pubkey "$TMP/c_user_pub.pem" --msg "interop" \
    --cred "$TMP/py2c_cred.pem" --issuer "$TMP/py_issuer_pub.pem"

check "Py cred → Py verify" \
    $CLI_PY cred-verify --proof "$TMP/c_proof.pem" \
    --pubkey "$TMP/c_user_pub.pem" --msg "interop" \
    --cred "$TMP/py2c_cred.pem" --issuer "$TMP/py_issuer_pub.pem"

if [ "$HAVE_GO" -eq 1 ]; then
    # Go issuer signs C user key at Go's own 219-round default (TODO #236;
    # see the note on the Python issuer above).
    "$CLI_GO" cred-issue --our "$TMP/go_issuer.pem" --in "$TMP/c_user_pub.pem" \
                        --out "$TMP/go2c_cred.pem" 2>/dev/null

    check "Go cred → C verify" \
        "$CLI_C" cred-verify --proof "$TMP/c_proof.pem" \
        --pubkey "$TMP/c_user_pub.pem" --msg "interop" \
        --cred "$TMP/go2c_cred.pem" --issuer "$TMP/go_issuer_pub.pem"

    check "Go cred → Py verify" \
        $CLI_PY cred-verify --proof "$TMP/c_proof.pem" \
        --pubkey "$TMP/c_user_pub.pem" --msg "interop" \
        --cred "$TMP/go2c_cred.pem" --issuer "$TMP/go_issuer_pub.pem"

    check "Go cred → Go verify" \
        "$CLI_GO" cred-verify --proof "$TMP/c_proof.pem" \
        --pubkey "$TMP/c_user_pub.pem" --msg "interop" \
        --cred "$TMP/go2c_cred.pem" --issuer "$TMP/go_issuer_pub.pem"

    # C issuer signs Go user key, Go verifies
    "$CLI_C" cred-issue --our "$TMP/c_issuer.pem" --in "$TMP/go_user_pub.pem" \
                        --out "$TMP/c2go_cred.pem" 2>/dev/null
    check "C cred (over Go key) → Go verify" \
        "$CLI_GO" cred-verify --proof "$TMP/go_proof.pem" \
        --pubkey "$TMP/go_user_pub.pem" --msg "interop" \
        --cred "$TMP/c2go_cred.pem" --issuer "$TMP/c_issuer_pub.pem"
fi

# Wrong-message rejection
check_fail "wrong-msg reject (C verifier)" \
    "$CLI_C" cred-verify --proof "$TMP/c_proof.pem" \
    --pubkey "$TMP/c_user_pub.pem" --msg "wrong"

check_fail "wrong-msg reject (Py verifier)" \
    $CLI_PY cred-verify --proof "$TMP/c_proof.pem" \
    --pubkey "$TMP/c_user_pub.pem" --msg "wrong"

if [ "$HAVE_GO" -eq 1 ]; then
    check_fail "wrong-msg reject (Go verifier)" \
        "$CLI_GO" cred-verify --proof "$TMP/c_proof.pem" \
        --pubkey "$TMP/c_user_pub.pem" --msg "wrong"
fi

# ── Summary ────────────────────────────────────────────────────────────────
echo ""
echo "Results: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ]
